### PR TITLE
refactor of extract_ngrams function

### PR DESCRIPTION
**Pull request by dellison**
Hey Nick,

Code looks good! In case you'd like it, here's a small rewrite I did of the extract_ngrams function. In my opinion, it improves the readability of the code a little bit (your mileage may vary on this one, I dunno).

It also fixes a bug: your code's 4-gram list always includes the grams '^^^^' and '$$$$' for each word, which will never contribute anything to your models.

It also runs a bit faster this way, too, since it doesn't need to do so many individual list lookups (although I think the extra grams account for some of this time too). I tested it with an artificial line of 500,000 words (['one', 'two', 'three', 'four', 'five'] repeated 100k times): your code ran in about 8s, and mine was about 4s.

Anyway, feel free to use (or rewrite, or whatever) the code if you'd like to! And if you don't want it it won't hurt my feelings either. :)

Hope this helps!

XOXO,
David

### CODE REVIEW

**Comment by kloehnen** [comment]
Hmm, I seem to have an error when I run it. The error is occurring within the calculate_mle function. It appears as though the index (i) of fivegrams is falling outside the range of fourgrams in the loop. I don't know if this has to do with the changes made in the string initial and string final markers. I'm assuming you're not getting this error...

:)

**Comment by dellison** [comment]
Oh, I didn't try running it end-to-end. I just wrote some little unit tests for the function that I changed. 

That makes sense, thought. I can't really go through it right now in TOO much detail since I'm at work, but it looks like that function is assuming that the lists "fourgrams" and "fivegrams" are the same length. This is no longer the case, since it's now excluding the dummy ^^^^ and $$$$ fourgrams.

Since it looks like you need to include those grams in your calculations of the probability estimates, the path of least resistance would probably just be to back out of my change. (This would not offend me.) `calculate_mle` appears to rely pretty heavily on both of the ngram lists being in a very particular order, so at a glance, I don't think you couldn't easily get this information back without rewriting some other things. Pragmatically, I'd suggest doing it this way, at least for the time being.

If you keep track of word counts in your model somewhere (instead of just grams), then you should be able to recover these counts very easily, since the counts of the "^^^^"  and "$$$$" grams will just be the same as the number of words that you've observed. This wouldn't be difficult to do, but it would be a little more code.

**Comment by dellison** [comment]
(To "back out of my change," you should just be able to do a `git revert 1548a28d3262f4002074d5e812de4f9f5e10c4c7` to undo the merge of my feature branch.

**Comment by kloehnen** [comment]
I fixed it. The MLE calculation was dependent upon the 4 gram being the prior of the 5gram. (^^do to ^^dog). So, I needed to have the same number of boundaries for both. Instead of having the boundary be dynamically calculated, I just hardcoded it as 4. Problem solved. But to adapt it to other size n-grams, it would have to be redesigned. Thanks!

**Pull request merged**
